export const SET_AVAILIABLE_VARIABLES = "SET_AVAILIABLE_VARIABLES";
export const CHANGE_SETTING = "CHANGE_SETTING";
export const SET_GEO_DATA = "SET_GEO_DATA";
export const CHANGE_SCREEN = "CHANGE_SCREEN";
